In [1]:
import pandas as pd
import numpy as np
from pandas_profiling import ProfileReport

In [2]:
data=pd.read_csv('drebin-215-dataset-5560malware-9476-benign_bhavishya_(1).csv')

c:\Program Files\Python36\lib\site-packages\IPython\core\interactiveshell.py:3072: DtypeWarning: Columns (92) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [3]:
data.head()

transact  onServiceConnected  bindService  attachInterface  \
0         0                   0            0                0   
1         0                   0            0                0   
2         0                   0            0                0   
3         0                   0            0                0   
4         0                   0            0                0   

   ServiceConnection  android.os.Binder  SEND_SMS  \
0                  0                  0         1   
1                  0                  0         1   
2                  0                  0         1   
3                  0                  0         0   
4                  0                  0         0   

   Ljava.lang.Class.getCanonicalName  Ljava.lang.Class.getMethods  \
0                                  0                            0   
1                                  0                            0   
2                                  0                            0   
3                                  0                            0   
4                                  0                            0   

   Ljava.lang.Class.cast  ...  READ_CONTACTS  DEVICE_POWER  HARDWARE_TEST  \
0                      0  ...              0             0              0   
1                      0  ...              0             0              0   
2                      0  ...              0             0              0   
3                      1  ...              0             0              0   
4                      0  ...              0             0              0   

   ACCESS_WIFI_STATE  WRITE_EXTERNAL_STORAGE  ACCESS_FINE_LOCATION  \
0                  0                       1                     0   
1                  0                       1                     0   
2                  0                       0                     0   
3                  1                       1                     1   
4                  1                       0                     1   

   SET_WALLPAPER_HINTS  SET_PREFERRED_APPLICATIONS  WRITE_SECURE_SETTINGS  \
0                    0                           0                      0   
1                    0                           0                      0   
2                    0                           0                      0   
3                    0                           0                      0   
4                    0                           0                      0   

   class  
0      S  
1      S  
2      S  
3      S  
4      S  

[5 rows x 216 columns]

In [4]:
# profile = ProfileReport(data)
# profile.to_file(output_file="job.html")

In [5]:
data.shape

(15036, 216)

In [6]:
data.duplicated

<bound method DataFrame.duplicated of        transact  onServiceConnected  bindService  attachInterface  \
0             0                   0            0                0   
1             0                   0            0                0   
2             0                   0            0                0   
3             0                   0            0                0   
4             0                   0            0                0   
...         ...                 ...          ...              ...   
15031         1                   1            1                1   
15032         0                   0            0                0   
15033         0                   0            0                0   
15034         1                   1            1                1   
15035         1                   1            1                1   

       ServiceConnection  android.os.Binder  SEND_SMS  \
0                      0                  0         1   
1                  

In [7]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
data['class']=le.fit_transform(data['class'])

In [8]:
data

transact  onServiceConnected  bindService  attachInterface  \
0             0                   0            0                0   
1             0                   0            0                0   
2             0                   0            0                0   
3             0                   0            0                0   
4             0                   0            0                0   
...         ...                 ...          ...              ...   
15031         1                   1            1                1   
15032         0                   0            0                0   
15033         0                   0            0                0   
15034         1                   1            1                1   
15035         1                   1            1                1   

       ServiceConnection  android.os.Binder  SEND_SMS  \
0                      0                  0         1   
1                      0                  0         1   
2                      0                  0         1   
3                      0                  0         0   
4                      0                  0         0   
...                  ...                ...       ...   
15031                  1                  1         0   
15032                  0                  0         0   
15033                  0                  0         0   
15034                  1                  1         0   
15035                  1                  1         0   

       Ljava.lang.Class.getCanonicalName  Ljava.lang.Class.getMethods  \
0                                      0                            0   
1                                      0                            0   
2                                      0                            0   
3                                      0                            0   
4                                      0                            0   
...                                  ...                          ...   
15031                                  1                            1   
15032                                  0                            0   
15033                                  0                            0   
15034                                  1                            1   
15035                                  1                            1   

       Ljava.lang.Class.cast  ...  READ_CONTACTS  DEVICE_POWER  HARDWARE_TEST  \
0                          0  ...              0             0              0   
1                          0  ...              0             0              0   
2                          0  ...              0             0              0   
3                          1  ...              0             0              0   
4                          0  ...              0             0              0   
...                      ...  ...            ...           ...            ...   
15031                      1  ...              0             0              0   
15032                      1  ...              0             0              0   
15033                      0  ...              0             0              0   
15034                      1  ...              1             0              0   
15035                      1  ...              0             0              0   

       ACCESS_WIFI_STATE  WRITE_EXTERNAL_STORAGE  ACCESS_FINE_LOCATION  \
0                      0                       1                     0   
1                      0                       1                     0   
2                      0                       0                     0   
3                      1                       1                     1   
4                      1                       0                     1   
...                  ...                     ...                   ...   
15031                  1                       1                     0   
15032                  1                       1   

In [9]:
d1=data.corr()

In [10]:
d1

transact  onServiceConnected  bindService  \
transact                    1.000000            0.810812     0.816442   
onServiceConnected          0.810812            1.000000     0.983198   
bindService                 0.816442            0.983198     1.000000   
attachInterface             0.963364            0.783617     0.791208   
ServiceConnection           0.813181            0.984796     0.994622   
...                              ...                 ...          ...   
ACCESS_FINE_LOCATION        0.121453            0.126678     0.128311   
SET_WALLPAPER_HINTS        -0.008323           -0.018780    -0.017788   
SET_PREFERRED_APPLICATIONS -0.005148           -0.002141    -0.001477   
WRITE_SECURE_SETTINGS      -0.000828            0.007813     0.008242   
class                      -0.570235           -0.561192    -0.558963   

                            attachInterface  ServiceConnection  \
transact                           0.963364           0.813181   
onServiceConnected                 0.783617           0.984796   
bindService                        0.791208           0.994622   
attachInterface                    1.000000           0.787798   
ServiceConnection                  0.787798           1.000000   
...                                     ...                ...   
ACCESS_FINE_LOCATION               0.119865           0.132108   
SET_WALLPAPER_HINTS               -0.011382          -0.018360   
SET_PREFERRED_APPLICATIONS        -0.002906          -0.001860   
WRITE_SECURE_SETTINGS              0.005000           0.006604   
class                             -0.551578          -0.557725   

                            android.os.Binder  SEND_SMS  \
transact                             0.881938 -0.274731   
onServiceConnected                   0.842693 -0.324517   
bindService                          0.848719 -0.321665   
attachInterface                      0.861441 -0.263826   
ServiceConnection                    0.848134 -0.322458   
...                                       ...       ...   
ACCESS_FINE_LOCATION                 0.102486 -0.008198   
SET_WALLPAPER_HINTS                 -0.021553  0.016163   
SET_PREFERRED_APPLICATIONS          -0.015285 -0.011377   
WRITE_SECURE_SETTINGS                0.000550  0.108017   
class                               -0.553786  0.545650   

                            Ljava.lang.Class.getCanonicalName  \
transact                                             0.656768   
onServiceConnected                                   0.644763   
bindService                                          0.649462   
attachInterface                                      0.642650   
ServiceConnection                                    0.646782   
...                                                       ...   
ACCESS_FINE_LOCATION                                 0.199319   
SET_WALLPAPER_HINTS                                  0.010440   
SET_PREFERRED_APPLICATIONS                          -0.035590   
WRITE_SECURE_SETTINGS                               -0.054999   
class                                               -0.467702   

                            Ljava.lang.Class.getMethods  \
transact                                       0.587103   
onServiceConnected                             0.596667   
bindService                                    0.599769   
attachInterface                                0.580424   
ServiceConnection                              0.599281   
...                                                 ...   
ACCESS_FINE_LOCATION                           0.196201   
SET_WALLPAPER_HINTS                            0.042286   
SET_PREFERRED_APPLICATIONS                    -0.001648   
WRITE_SECURE_SETTINGS                         -0.070511   
class                                         -0.436442   

                            Ljava.lang.Class.cast  ...  READ_CONTACTS  \
transact                                 0.613781  ...       0.068374   
onServiceConn

In [11]:
# d1.to_csv('correlation.csv')

In [12]:
data=data[['SEND_SMS','android.telephony.SmsManager','READ_PHONE_STATE','RECEIVE_SMS','READ_SMS','android.intent.action.BOOT_COMPLETED','TelephonyManager.getLine1Number','WRITE_SMS','WRITE_HISTORY_BOOKMARKS','TelephonyManager.getSubscriberId','android.telephony.gsm.SmsManager','INSTALL_PACKAGES','READ_HISTORY_BOOKMARKS','INTERNET','ACCESS_LOCATION_EXTRA_COMMANDS','WRITE_APN_SETTINGS','class']]

In [28]:
data.to_csv('final.csv')

In [13]:
data.head()

SEND_SMS  android.telephony.SmsManager  READ_PHONE_STATE  RECEIVE_SMS  \
0         1                             1                 1            0   
1         1                             1                 1            1   
2         1                             1                 1            0   
3         0                             0                 1            0   
4         0                             0                 1            0   

   READ_SMS  android.intent.action.BOOT_COMPLETED  \
0         0                                     1   
1         1                                     1   
2         0                                     0   
3         1                                     1   
4         0                                     1   

   TelephonyManager.getLine1Number  WRITE_SMS  WRITE_HISTORY_BOOKMARKS  \
0                                0          0                        0   
1                                0          0                        0   
2                                0          0                        0   
3                                1          1                        0   
4                                0          0                        1   

   TelephonyManager.getSubscriberId  android.telephony.gsm.SmsManager  \
0                                 0                                 0   
1                                 0                                 0   
2                                 0                                 0   
3                                 1                                 0   
4                                 0                                 0   

   INSTALL_PACKAGES  READ_HISTORY_BOOKMARKS  INTERNET  \
0                 0                       0         1   
1                 0                       0         1   
2                 0                       0         1   
3                 1                       0         1   
4                 0                       1         1   

   ACCESS_LOCATION_EXTRA_COMMANDS  WRITE_APN_SETTINGS  class  
0                               0                   0      1  
1                               0                   0      1  
2                               0                   0      1  
3                               1                   0      1  
4                               0                   0      1

In [14]:
data.shape

(15036, 17)

In [27]:
data['class'].value_counts()

0    9476
1    5560
Name: class, dtype: int64

In [15]:
import matplotlib.pyplot as plt
import seaborn as sns
plt.figure(figsize=(20,20))
d = sns.heatmap(data.corr(),cmap="coolwarm",annot= True)
plt.savefig('corr.png')

In [16]:
y = data['class']
x = data.drop(['class'], axis = 1) 

In [17]:
from sklearn.model_selection import train_test_split

In [18]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3,stratify=y, random_state= 42)  

In [19]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score,confusion_matrix
dt = DecisionTreeClassifier()
dt = dt.fit(x_train,y_train)
y_pred = dt.predict(x_test)
acc_dt = accuracy_score(y_test,y_pred)
print('The accuracy obtained by the Decision Tree Classifier:',acc_dt)
cm = confusion_matrix(y_test,y_pred)
print(cm)

The accuracy obtained by the Decision Tree Classifier: 0.9075592994901353
[[2653  190]
 [ 227 1441]]


In [20]:
from xgboost import XGBClassifier
xgb = XGBClassifier()
xgb = xgb.fit(x_train,y_train)
y_pred = xgb.predict(x_test)
acc_xgb = accuracy_score(y_test,y_pred)
print('The accuracy obtained by the XGBoost Classifier is:',acc_xgb)
cm = confusion_matrix(y_test,y_pred)
print(cm)

[12:55:55] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.4.0/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


c:\Program Files\Python36\lib\site-packages\xgboost\sklearn.py:1146: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


The accuracy obtained by the XGBoost Classifier is: 0.9060075371314564
[[2648  195]
 [ 229 1439]]


In [21]:
from sklearn.ensemble import AdaBoostClassifier
adb = AdaBoostClassifier()
adb = adb.fit(x_train,y_train)
y_pred = adb.predict(x_test)
acc_adb = accuracy_score(y_pred,y_test)
print('The accuracy obtained by the AdaBoost Classifier is :',acc_adb)
cm = confusion_matrix(y_test,y_pred)
print(cm)

The accuracy obtained by the AdaBoost Classifier is : 0.8324096652626912
[[2626  217]
 [ 539 1129]]


In [22]:
from sklearn.svm import SVC 
svc = SVC(kernel='linear')
svc = svc.fit(x_train,y_train)
y_pred = svc.predict(x_test)
acc_svc = accuracy_score(y_test,y_pred)
print('The accuracy obtained by the Support Vector Classifier is :',acc_svc)

The accuracy obtained by the Support Vector Classifier is : 0.8348481489691865


In [23]:
abc = [0,	0,	0,	0,	0,	1,	0,	0,	0,	0,	0,	0,	0,	1,	0,	0]
result = dt.predict([abc])
result

array([0])

In [24]:
abc = [1,	0,	1,	1,	1,	1,	1,	1,	0,	1,	1,	1,	0,	1,	1,	0]
result = dt.predict([abc])
result

array([1])

In [25]:
x_train

SEND_SMS  android.telephony.SmsManager  READ_PHONE_STATE  RECEIVE_SMS  \
7217          0                             0                 0            0   
11311         0                             0                 1            0   
3020          1                             0                 1            1   
13841         0                             0                 0            0   
13269         0                             0                 1            0   
...         ...                           ...               ...          ...   
3266          1                             0                 1            1   
14182         0                             0                 0            0   
11026         0                             0                 0            0   
10622         0                             0                 1            1   
3032          0                             0                 1            0   

       READ_SMS  android.intent.action.BOOT_COMPLETED  \
7217          0                                     1   
11311         0                                     0   
3020          1                                     1   
13841         0                                     0   
13269         0                                     0   
...         ...                                   ...   
3266          0                                     0   
14182         0                                     0   
11026         0                                     0   
10622         0                                     1   
3032          0                                     0   

       TelephonyManager.getLine1Number  WRITE_SMS  WRITE_HISTORY_BOOKMARKS  \
7217                                 0          0                        0   
11311                                0          0                        0   
3020                                 1          1                        0   
13841                                0          0                        0   
13269                                1          0                        0   
...                                ...        ...                      ...   
3266                                 0          0                        1   
14182                                0          0                        0   
11026                                0          0                        0   
10622                                1          0                        0   
3032                                 0          0                        0   

       TelephonyManager.getSubscriberId  android.telephony.gsm.SmsManager  \
7217                                  0                                 0   
11311                                 0                                 0   
3020                                  1                                 1   
13841                                 0                                 0   
13269                                 1                                 0   
...                                 ...                               ...   
3266                                  1                                 1   
14182                                 0                                 0   
11026                                 0                                 0   
10622                                 0                                 0   
3032                                  0                                 0   

       INSTALL_PACKAGES  READ_HISTORY_BOOKMARKS  INTERNET  \
7217                  0                       0         1   
11311                 0                       0         1   
3020                  1                       0         1   
13841                 0                       0         0   
13269                 0                       0         1   
...                 ...                     ...       ...   
3266                  1                       1         1   
14182      

In [26]:
y_train

7217     0
11311    0
3020     1
13841    0
13269    0
        ..
3266     1
14182    0
11026    0
10622    0
3032     1
Name: class, Length: 10525, dtype: int32